### ISSUE TITLE
generator is pulling in all files, including those in .gitignore

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-cli#108]
With the latest CLI and rug, I'm generating a project and it's getting target/ even though it is in the .gitignore

**Comment by cdupuis** [comment]
If remember correctly, we agreed that we stop filtering based on gitignore and use ignore in .atomist only. Have you tried putting target into ignore?

**Comment by jessitron** [comment]
oh okay! Is it .atomistignore?

**Comment by kipz** [comment]
Just `ignore` AFAIR

**Comment by jessitron** [comment]
thanks! Worked!
