### ISSUE TITLE
CLI doesn't display usage when no arguments are provided

### ISSUE THREAD

**Issue by Lawouach** [atomist/rug-cli#109]
Since the upgrade to 0.23.0, the CLI doesn't display its usage when no arguments are passed:

```
$ rug --version
rug 0.23.0
https://github.com/atomist/rug-cli.git (git revision e77cf5f; last commit 2017-02-14)

$ rug

com/atomist/rug/compiler/Compiler
```

The previous versions would display the usage as expected.

**Comment by ddgenome** [comment]
Some consider it bad form to display the whole usage when not asked. If no or invalid output is supplied, they recommend suggesting the `--help` option. For example,

```
$ rug
Missing subcommand argument
Try `rug --help` for more information.
```

Nonetheless, many programs do display the help output in that scenario.

**Comment by Lawouach** [comment]
I'm fine with this definitely.

**Comment by cdupuis** [comment]
Yeah, that is good point @ddgenome
