### ISSUE TITLE
Enable CLI to work on Windows

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-cli#11]
It appears that there are a few places where the CLI currently fails on Windows.
This has to do with file path handling etc.

Also $HOME env variable doesn't expand on Windows.

**Comment by Lawouach** [comment]
Indeed. Though, luckily, I could only find one occurence which was a problem. Iin the cli.yml file that gets copied over, we have that entry:

```
 path: "${HOME}/.atomist/repository"
```

This fails on Windows and makes the CLI to crash. I was initially tempted to replace it like this:

```
 path: "%USERPROFILE%\\.atomist\\repository"
```

But, for some reason, that doesn't work. Probably the % which triggers string interpolation?

The following works:

```
 path: "C:\\Users\\Sylvain\\.atomist\\repository"
```

Notice that C:\\Users\\Sylvain is the actual value of %USERPROFILE%. Ideally, we should support the syntax with %USERPROFILE%, but if not, when the file gets copied over, we should update that entry accordingly with the absolute path.

**Comment by cdupuis** [comment]
@Lawouach, with this fixed up file you were able to use the CLI on Windows?

**Comment by Lawouach** [comment]
Yes. With the absolute path, that worked fine as far as I could test. If we can make it work with the actual %USERPROFILE% env variable, this would look even better of course.

**Comment by cdupuis** [comment]
I would vote for ${user.home} as this is platform independent.

**Comment by cdupuis** [comment]
@Lawouach can you test 5f9d7ed2e147d039ed37d4a1a8d2b2acd2e5f4ff please and let me know what you see.

**Comment by Lawouach** [comment]
This works fine as far as I could see.

**Comment by Lawouach** [comment]
Verified in 0.14.0.
