### ISSUE TITLE
rug --help not helpful on new install

### ISSUE THREAD

**Issue by acolyer** [atomist/rug-cli#110]
After a fresh install of the rug-cli with `brew install rug-cli`, issuing `rug --help` just produces the output:

>  
> com/atomist/rug/compiler/Compiler

This is with rug 0.23.0, https://github.com/atomist/rug-cli.git (git revision e77cf5f; last commit 2017-02-14)

**Comment by cdupuis** [comment]
https://github.com/atomist/rug-cli/issues/109

**Comment by acolyer** [comment]
It's very close to #109, but not quite the same - note that I'm explicitly passing the --help option. Although I can imagine the fix is the same!

**Comment by cdupuis** [comment]
Yeah, it is the same. I'll prep a new CLI release today.
