### ISSUE TITLE
shell history navigation does not behave properly after typing something

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#113]
The shell history navigation does not behave as expected when using it after you type something. I expect that, even after typing something, up arrow and Ctrl-P will navigate to the previous command. Ctrl-P does this but up arrow searches the command history for commands that start with what you have typed.

I expect both history commands to behave the same and like they do in Bash: navigate to the previous history item regardless of how it matches what I have previously typed.

If this behavior is hard-coded into JLine3, it may be hard to correct.

I love being able to escape into a shell using `!` by the way.

**Comment by cdupuis** [comment]
That is on purpose inside Jline and it is also how my shell behaves. Is that really a bug or more an opinion ;-) ?

**Comment by ddgenome** [comment]
What shell are you using? I'm using Bash with default readline behavior, which behaves as I describe: up arrow/Ctrl-P cycle through all the history regardless of what I current have typed.

I don't think it is a big deal either way, it was just surprising behavior to me.

**Comment by cdupuis** [comment]
I'm on bash with some fancy history extension which is probably where I'm getting that behaviour from.

**Comment by cdupuis** [comment]
Closing this for now as there is apparently no way of doing this right now.
