### ISSUE TITLE
Publish rug-cli docker image as part of the build

### ISSUE THREAD

**Issue by kipz** [atomist/rug-cli#115]
Some folk can't/don't want to upgrade java or otherwise put a bunch a (as yet) untrusted stuff on their machines. Docker would be a nice solution to this.

**Comment by kipz** [comment]
@Lawouach - do you have any thoughts on how best to do this?

**Comment by Lawouach** [comment]
If we can create something using an Alpine base, that would make such an image small(ish). Like this one https://github.com/docker-library/openjdk/blob/0476812eabd178c77534f3c03bd0a2673822d7b9/8-jdk/alpine/Dockerfile

**Comment by jhuiting** [comment]
Built a similar image a while ago, that is built on top of Alpine JDK 8. Probably would add Docker-compose as well to make running the image easier.

```
FROM openjdk:8-jdk-alpine

RUN MAVEN_VERSION=3.3.3 \
 && cd /usr/share \
 && wget http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz -O - | tar xzf - \
 && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_OPTS "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true $MAVEN_OPTS"
RUN apk update && \
    apk add bash unzip && \
    rm -rf /var/cache/apk/*
```
