### ISSUE TITLE
shell completion should not show options until second tab

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#120]
Currently when you press tab to complete what you have typed thus far, it completes what it can unambiguously and displays all possible completions. Typical completion semantics do not display the possible completions until the second time tab is pressed.

**Comment by cdupuis** [comment]
It is not obvious from the code how I could do that. I've sent a question about this to the jline-users mailing list.

**Comment by cdupuis** [comment]
hmm, We can change the tab-completion to double-tab but that would also mean that unambiguous word completions are only complete on double-tab. Is that what you would expect @ddgenome?

**Comment by ddgenome** [comment]
So pressing <Tab> once would do nothing? That would be bad. I'd prefer the current behavior.

**Comment by cdupuis** [comment]
So, I'm not sure what we should make with this here then?

**Comment by ddgenome** [comment]
If there's no way to have the common default behavior, I'd suggest leaving it as is.

**Comment by cdupuis** [comment]
Closing this for now until we maybe get some more requests on this.
