### ISSUE TITLE
Add command to display path expression to a point in a file within a project

### ISSUE THREAD

**Issue by johnsonr** [atomist/rug-cli#123]
This will be very useful to help users develop path expressions and editors.

A new method on Rug's `ProjectMutableView` has the following signature:

```def pathTo(path: String, kind: String, lineFrom1: Int, colFrom1: Int): String```

This can underpin a command to display a path to a position in a file. E.g. for

```
path=/src/main/scala/myco/FooBar.scala
kind=ScalaFile
lineFrom1=26
colFrom1=14
```

It will produce output like

```/File()[@path='/src/main/scala/myco/FooBar.scala']/ScalaFile()[1]/defnClass[1]/template[1]/defnDef[1]/termBlock[1]/termTryWithCases[1]/termBlock[1]/termApply[1]```

**Comment by cdupuis** [comment]
Implemented in c0be46c06ea9b4b64e8b1bd8bfbb4b4455161249
