### ISSUE TITLE
JAVA_OPTS proxy settings not working

### ISSUE THREAD

**Issue by dzonekl** [atomist/rug-cli#128]
Hi, 

We don't get working behind our proxy, Our proxy is HTTP only (not https), Could this be the problem looking at the src code? 

Edit: It seems rug-cli is doing something with maven repositories with ```rug-cli list``` command , so I guess this is a proxy setting for maven. 

Rgds Christophe

**Comment by dzonekl** [comment]
Hi, 

After a rather long debug session, I found rug-cli uses eclipse.aether, and default JreProxySelector, which dependends on ProxySelector.setDefault()

So adding this code just before the DependencyResolverFactory creates a Resolver solves my problem: (In class ReflectiveCOmmandRunner). 

```java
private List<ArtifactDescriptor> resolveDependencies(ArtifactDescriptor artifact,
            ProgressReporter indicator) {

        ProxySelector.setDefault(new ProxySelector() {
            @Override
            public List<Proxy> select(URI uri) {
                return Collections.singletonList(new Proxy(Proxy.Type.HTTP,new InetSocketAddress("http://host", 8080)));
            }

            @Override
            public void connectFailed(URI uri, SocketAddress sa, IOException ioe) {
                log.error("Proxy config failed", ioe);
            }
        });
```

**Comment by cdupuis** [comment]
hey, thanks for taking the time to hunt this down. We are dealing with proxies but maybe not in a way that works for you. Did you see 
`resolver.setProxySelector(new ConservativeProxySelector(new JreProxySelector()));` in https://github.com/atomist/rug-cli/blob/master/src/main/java/com/atomist/rug/cli/resolver/DependencyResolverFactory.java#L69

See for configuring the proxy options: http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html

**Comment by cdupuis** [comment]
You should be able to use the following command to setup your proxy:

`export JAVA_OPTS=-Dhttp.proxyHost=host -Dhttp.proxyPort=8080`

Does that not work?

**Comment by dzonekl** [comment]
nope it doesn't (see title of the issue :-) 
Simply because,  indeed the java ProxySelector is used, see my 2nd comment

**Comment by cdupuis** [comment]
Ok, let me debug that and see what is going on.

**Comment by cdupuis** [comment]
We are using both, http and https repo urls per default in the CLI and therefore you need to specify both types of proxy:

`export JAVA_OPTS=-Dhttp.proxyHost=host -Dhttp.proxyPort=8080 -Dhttps.proxyHost=host -Dhttps.proxyPort=8080`

**Comment by dzonekl** [comment]
Thanks this works! I am curious to understand, how the JreProxySelector and underlying JDK ProxySelector picks up these properties.

**Comment by cdupuis** [comment]
By default the JDK install a `sun.net.spi.DefaultProxySelector` which picks up those properties. See http://hg.openjdk.java.net/jdk8u/hs-dev/jdk/file/3eb4e20b34cb/src/share/classes/sun/net/spi/DefaultProxySelector.java for source code.

This makes me think though, I don't really like the fact that people need to understand Java `-D` parameters and how to set them. I wonder if we should make proxy configuration a first class concern and have a section for those in the `cli.yml` file. WDYT

**Comment by dzonekl** [comment]
Ah, yes I coudn't see the content of the DefaultProxySelector in my debug sessions (As it was wrapped in a Resolver, and source code was missing for aether). Anyway, yes the -D properties is not very friendly. I think http proxy should be read from the OS (As it's often set with an http proxy auto configure pac file). I believe there are Java libs for this. Any extra SW specific configuration shoudn't be necessary in my opinion. I.e. browsers work out of the box with OS proxy config. Most bash, java etc.. based sw is very often a problem. For Maven I need to change settings.xml, Docker is also still struggling with this (Mac OS docker native) etc...

**Comment by cdupuis** [comment]
Hmm, that should actually work by setting `-Djava.net.useSystemProxies=true`. Can you try that too?

**Comment by dzonekl** [comment]
I tried it and it works as well :-) So perhaps an option in cli.yml to turn this on/off?

**Comment by cdupuis** [comment]
I made the `-Djava.net.useSystemProxies=true` the default in the rug scripts. This can be overridden by `export RUG_OPTS=`.

See cb7f742db1bdabaa2a0814d021ace5e996448f1d
