### ISSUE TITLE
Running tests failing when ~/.atomist/ext exists

### ISSUE THREAD

**Issue by Lawouach** [atomist/rug-cli#129]
I was trying to run the tests with `mvn clean tests` today and they were constantly failing, only when I removed `~/.atomist/ext` directory did the tests pass again.

Tests should not be failing when extensions are on the system.

**Comment by cdupuis** [comment]
What is the stack trace or failure you are seeing?

**Comment by Lawouach** [comment]
Unfortunately, I don't have it any more. But it couldn't find a class CommandInfo or something when running the tests. Turned out, I had deployed the rug handler cli extension before and it was relying on old versions of rug and the CLI. I guess the CLASSPATH tried to load it anyway and failed in doing so.
