### ISSUE TITLE
Minor: complains when no TTY

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#130]
When building the docker image on Travis, `rug search` is executed and the CLI complains that there is no TTY.

https://travis-ci.org/atomist/rug-cli/builds/203532755#L9298

```
/home/atomist/rug-cli-0.24.0/bin/rug: line 99: /dev/tty: No such device or address
Feb 20, 2017 5:47:50 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Resolving dependencies for com.atomist:rug:0.12.0
...
```

This line appears to be the culprit:

```sh
COLUMNS=`tput cols 2> /dev/tty`
```

**Comment by cdupuis** [comment]
@ddgenome do you have any idea how to fix that?

**Comment by ddgenome** [comment]
I'm not sure why it is being sent to `/dev/tty` to begin with. Perhaps it should be to `/dev/null`? I am happy to fix it either way, it's just I don't it if is OK to replace `/dev/tty` with `/dev/null`.

**Comment by cdupuis** [comment]
Hmm, I might actually be a able to completely remove this. We have JLine now and it has the capability to give us the terminal width.

**Comment by ddgenome** [comment]
I've created a PR to use `/dev/null`. Feel free to disregard and go the JLine route.
