### ISSUE TITLE
install / deploy commands archive too much files

### ISSUE THREAD

**Issue by dandew** [atomist/rug-cli#148]
Any file/directory that happens to be in the project, even if starting with `.`, is getting archived in the rug zip. So currently one has to remember to run `git clean -fdx .` prior to `rug install` or `rug deploy` to avoid packaging temporary / test files that could happen to be in the project (think of `.out` directory where the outcome of `rug generate` is stored).

It would be nice to be able to skip some files/directories, for example by honouring`.gitignore`.

**Comment by cdupuis** [comment]
We discussed doing filtering based `.gitignore` files automatically earlier in this project but realised that this would actually not work well: it is best practice to not commit your `node_modules` into git and that means it usually ends up in the `.gitignore` file. But `node_modules` is needed at runtime and therefore that would pretty much break people when they start to use Rug.

Having said that, you can use a file called `ignore` (without a leading `.`) in `.atomist` to exclude things from being handed over to Rug for packaging etc. Pattern and paths you put into `ignore` will be anchored in the root of your project. 

Hope that helps?

**Comment by dandew** [comment]
Sorry I missed the `.atomist/ignore` file, it works great, thank you!

**Comment by cdupuis** [comment]
Thanks for confirming. This is easy to miss as we haven't documented that at all.
