### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by jwalter** [atomist/rug-cli#149]
Links to "Rug CLI documentaion", "Rug CLI Quick Start" and "Rug CLI Installation" all ends up at a 404 page

**Comment by jessitron** [comment]
thanks for reporting this!

**Comment by jessitron** [comment]
Fixed. @ddgenome I linked to your blog post https://the-composition.com/rugs-on-the-command-line-eca46492db09#.9ke4rijhd in place of the "Rug CLI Quick Start" since the new docs don't have quick start afaict.

**Comment by jwalter** [comment]
Link to Rug CLI Installation is still broken

**Comment by jessitron** [comment]
thank you! fixed that one too.

**Comment by ddgenome** [comment]
Sorry for the breakage!

New install: http://docs.atomist.com/user-guide/interfaces/cli/install/
New "quick-start" that is no longer under Quick Starts: http://docs.atomist.com/user-guide/interfaces/cli/developing-rugs/
