### ISSUE TITLE
Dump all commands and options

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#151]
Is it possible to have the CLI or its build dump all of the CLI's commands and options in markdown or HTML? I'd like to have the reference documentation for the CLI to be generated automatically.

http://docs.atomist.com/reference/rug-cli/

**Comment by cdupuis** [comment]
There is a start of this in `CommandUtils.main`. That needs some polishing but gives a rough idea on how that could work.

Do you have a certain layout in mind?

**Comment by ddgenome** [comment]
If you just spit out Markdown and let the static site generator handle the layout, that would be fine.

**Comment by ddgenome** [comment]
If you'd like me to have a go at doing this, let me know.

**Comment by ddgenome** [comment]
@cdupuis is it OK to edit that `CommandUtils.main()` or is that used for something and you'd prefer  I code it up somewhere else?

**Comment by cdupuis** [comment]
No, this part isn't used for anything really. I put it in to make sure the bash completion is easy to maintain. You can go ahead to implement it in there or implement a new class somewhere else. Up to you.
