### ISSUE TITLE
Cached target files lead to spurious compilation success

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#156]
After the rug 0.13.0 upgrade, I saw several instances of compilation and testing succeeding locally but failing on Travis CI.

https://travis-ci.org/atomist-rugs/rug-upgrade/builds/211156120
https://travis-ci.org/atomist-rugs/rug-editors/builds/210611861

The behavior on Travis was appeared to be correct, i.e., the errors it was reporting during compilation were correct.

I tried to get the correct behavior locally by first deleting `.atomist/node_modules` and recreating with `$ npm install`. Compilation and testing still erroneously worked locally. I then went nuclear and deleted `.atomist/target`, `.atomist/node_modules`, and `~/.atomist`. At that point I was getting the correct behavior locally: compilation failures. Trying to narrow down the issue, I restored my original `~/.atomist` and still saw the proper behavior: failed compilation.

My guess is that the CLI is not recompiling .ts files that are older than the generated .jq and .map files under `.atomist/target/.jscache`. The cache logic should probably be updated to consider the timestamp and/or version of the files under `.atomist/node_modules`.

**Comment by cdupuis** [comment]
Cache logic is in rug-typescript-compiler. I wonder if we should just provide a clean command?

**Comment by ddgenome** [comment]
Whoops, I meant to click comment.

I think a `clean` command makes sense.

**Comment by ddgenome** [comment]
The cached files in `target` are definitely the culprit. Got caught by it again, https://travis-ci.org/atomist-rugs/rug-editors/builds/211515966 , removed the target directory and saw the same, appropriate, failure.

**Comment by cdupuis** [comment]
Do you have a way to re-produce this?

**Comment by ddgenome** [comment]
1.  Checkout out rug-editors tag 0.15.0
2.  `(cd .atomist && npm install)`
3.  `rug test -urX`
4.  Change manifest.yml and package.json to use rug 0.14.0
2.  `(cd .atomist && npm install)`
5.  `rug test -urX` <= will succeed when it should not
6.  `rm -rf .atomist/target`
5.  `rug test -urX` <= will fail as it should

**Comment by cdupuis** [comment]
Added `clean` command in 528ce9f2d04b0bc52cdaa555d143456c7b4686ab

**Comment by cdupuis** [comment]
We agreed that for now we'll provide the `clean` command.
