### ISSUE TITLE
Allow for excluding Rugs from the archive metadata

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#160]
As a Rug developer, I would like to exclude some Rugs from the Rug archive metadata that is used by search. Specifically, the rug-editors project has a use case for excluding the prototype Rugs used by editors like AddTypeScriptEditor and AddTypeScriptGenerator. We want the prototype Rugs to be compiled and tested just like all other Rugs in the project so we can ensure they are always valid and working, but we do not want people to run them as is. Therefore, it would be best if they did not show up in search results or describe output.

**Comment by ddgenome** [comment]
Perhaps we could use the tags on the Rug. For example, add a tag like `metadata:exclude` or `rug:hidden`.

**Comment by cdupuis** [comment]
What about putting a new key into the manifest.yml? Something like:

```
hidden:
  editors:
  - "AddTypeScriptEditor"
```

**Comment by ddgenome** [comment]
I like that better than using tags.

**Comment by cdupuis** [comment]
```
exclude:
  editors:
  - "AddTypeScriptEditor"
```

Ok?

**Comment by cdupuis** [comment]
I think this feature would helps us to reduce the flurry of editors and really only work as part of an editor. Would make the listing in the bot a lot cleaner.
