### ISSUE TITLE
Disallow publishing when with uncommitted local changes

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-cli#168]
Can we require publishing to be a commit, and require or create a tag?
I confuse myself by publishing without a commit, plus  anyone else who would be like "what code is behind this"
I still have to push, but I can't possibly do it right if I don't even have the code on a commit.

**Comment by cdupuis** [comment]
Plan is to use the "rug publish" from the bot again.

What we could enforce is that we can't publish on a working tree with un-committed changes.

**Comment by ddgenome** [comment]
While I don't want people publishing things that are not committed, I don't know if disallowing it, at least without the ability to override, is a good idea. While we want to encourage good practices, we do not want to force people to use our workflow, or git for that matter.

**Comment by cdupuis** [comment]
Yes, there has to be an option to disable the check. I totally agree.

**Comment by cdupuis** [comment]
To achieve this, we really only need a commit as the Git info makes it into the manifest.yml on publication.

**Comment by cdupuis** [comment]
Implemented in 0efc1cad9b9d47fd3a2c8877de34b1e4fe98c5bc
