### ISSUE TITLE
Align command and option names

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-cli#172]
In an effort to align all commands to _VERB [NOUN]_ structure, there are few commands
that stand out:

 * `dependencies`
 * `repositories`
 * `default`

I'd propose to change those commands to:

  * `dependencies -> describe dependencies`
  * `repositories login -> login`
  * `repositories configure -> configure repositories`
  * `default -> configure default archive`

(_updated after review comments_)

**Comment by cdupuis** [comment]
cc @ddgenome @WillGardella @kipz @jessitron

**Comment by ddgenome** [comment]
Sounds reasonable. Perhaps have stubs for the old ones pointing to the new ones for a time.

**Comment by kipz** [comment]
`default` / `configure default` is a bit misleading to me - default what? How about:

`configure default-archive`?

**Comment by cdupuis** [comment]
> Sounds reasonable. Perhaps have stubs for the old ones pointing to the new ones for a time.

That's a good idea. I have have to see how much work that is.

I think all those commands are usually not target for scripting. So maybe that is not such a big issue after all.

**Comment by ddgenome** [comment]
By "pointing to" I mean, "print out a message saying this command has moved to ..." and exit non-zero not "automagically call the command that replaces this", unless the latter is easy and can also be accompanied with a deprecation warning.

**Comment by WillGardella** [comment]
I prefer `show` to `describe` - it's shorter but is close enough, and it's the same as the `git` command so hopefully people would find it intuitive. 
`show dependencies`

I don't like commands that have hyphens - they're harder to type, and I think we don't need any in the Bot (we have some now but I would like to get rid of the dashes). The docker / git style here would be something like 

`configure default archive`, which leaves room to configure other types of defaults, and the space is easier to type. How does that strike you?

**Comment by cdupuis** [comment]
The CLI `describe` is different to the bot `show` in that it actually describes all the details of a Rug. I think that justifies keeping those two commands different. 

`configure default archive` works for me.

**Comment by ddgenome** [comment]
`describe` makes sense to me and is already established in the CLI.

**Comment by WillGardella** [comment]
`describe` is fine. Let me know if there's any other questions, otherwise I think we've discussed all the changes I can think of to the CLI

**Comment by cdupuis** [comment]
Here's the updated `help` output:

```
atomist-rugs:sandbox (0.11.0·local·0.25.3)
rug → help
Usage: [OPTION]... [COMMAND]...
Work with Rugs like editors or generators.

Options:
  -?,-h,--help  Print usage help
  -v,--version  Print version information

Available commands:
  search     Search online catalog of available archives
  list       List locally installed archives
  describe   Print details about an archive or Rug

  generate   Run a generator to create a new project
  edit       Run an editor to modify an existing project
  test       Run test scenarios
  clean      Clean up project
  install    Create and install an archive into the local repository
  publish    Create and publish an archive into a remote repository

  path       Evaluate a path expression against a project
  to path    Display path expression to a point in a file within a project

  login      Login using GitHub authentication
  configure  Change/manage configuration settings
  extension  Manage command line extensions

  command    Run a Command Handler
  trigger    Trigger an Event Handler

  shell      Start a shell for a specified Rug archive
  exit       Exit a shell session

  help       Print usage help

Available gestures:
  generate rug project  Generate a new Rug project with TypeScript support
  clone rug project     Clone an existing Rug project from GitHub and set up
                        TypeScript support

Run 'COMMAND --help' for more detailed information on COMMAND.

This shell supports event expansion with '!' and executing other commands by
prefixing the command with '/', eg. '/cd .atomist && ls -la'.

Please report issues at https://github.com/atomist/rug-cli
atomist-rugs:sandbox (0.11.0·local·0.25.3)
```

for your review @WillGardella
