### ISSUE TITLE
Missing testing Given/When steps are not reported

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#177]
The CLI properly reports unimplemented `Then` steps, but does not report missing `Given` or `When` steps. Could this be added?

**Comment by cdupuis** [comment]
I guess that is more a Rug bug, isn't it? The CLI doesn't do anything with regards to reporting. It relies purely on Rugs GherkinRunner. 

I guess we have to take a look where this info gets lost.

**Comment by cdupuis** [comment]
See https://github.com/atomist/rug/issues/570
