### ISSUE TITLE
Files do not seem to get properly deleted when running editors in CLI

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#179]
I've run into an issue where calling `project.deleteFile("foo")` in an editor does not delete an existing file `foo` from the project. You can reproduce with the following commands.

```
$ mkdir -p foo/.atomist/build
$ touch .atomist/{manifest.yml,package.json,build/cli-{build,dev,release}.yml}
$ rug --version
rug 0.33.4
https://github.com/atomist/rug-cli.git (git revision 552e380; last commit 2017-04-24)
$ rug edit atomist:rug-editors:UpdateSupportFiles
Resolving dependencies for atomist:rug-editors (latest·zip) completed
Loading atomist:rug-editors (0.28.0-20170425000942·zip) completed
Running editor UpdateSupportFiles of atomist:rug-editors (0.28.0-20170425000942·zip) completed

→ Project
  ~/tmp/foo/ (6 kb in 8 files)

→ Changes
  ├── .atomist/tsconfig.json created (752 bytes)
  ├── .atomist/tslint.json created (315 bytes)
  ├── .atomist/.gitignore created (41 bytes)
  ├── .atomist/build/cli.yml created (572 bytes)
  ├── .atomist/build/travis-build.bash created (4 kb)
  ├── .atomist/package.json.tmp created (102 bytes)
  ├── .atomist/package.json updated (145 bytes)
  └── .atomist.yml created (608 bytes)

Successfully edited project foo
$ tree -a
.
├── .atomist
│   ├── .gitignore
│   ├── build
│   │   ├── cli-build.yml
│   │   ├── cli-dev.yml
│   │   ├── cli-release.yml
│   │   ├── cli.yml
│   │   └── travis-build.bash
│   ├── manifest.yml
│   ├── package.json
│   ├── package.json.tmp
│   ├── tsconfig.json
│   └── tslint.json
└── .atomist.yml

2 directories, 12 files
```

The three `cli-{build,dev,release}.yml` files remain despite them being explicitly removed https://github.com/atomist/rug-editors/blob/master/.atomist/editors/UpdateSupportFiles.ts#L34-L41 . The rug-editors BDD tests to test to make sure these files are deleted and are successful.

Another perhaps related issue is that the UpdateSupportFiles editor creates a temporary file so it can load its contents and then calls `project.deleteFile()` on it. Again BDD tests in the project ensuring the file does not exist pass but the temporary file remains in the project (the `package.json.tmp` file above). https://github.com/atomist/rug-editors/blob/master/.atomist/editors/UpdateSupportFiles.ts#L67

**Comment by cdupuis** [comment]
I can confirm that this has indeed been fixed.
