### ISSUE TITLE
Automatically update CLI reference documentation

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#181]
On a Rug CLI release, automatically update the Rug CLI reference documentation in the end-user-documentation repo.

**Comment by cdupuis** [comment]
@ddgenome ping? Is this still open?

**Comment by ddgenome** [comment]
It's way open. Haven't had time to look at it. I'll get it done, someday.

**Comment by cdupuis** [comment]
fair enough. I just thought I saw you posting somewhere about it.
