### ISSUE TITLE
Extend archive metadata

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-cli#185]
I'd like to propose the following additional fields in the `manifest.yml`:

 * description - short description
 * tags - list of tags
 * homepage - url to homepage
 * issues - url to issue tracker
 * authors - list of authors in form `Name <email>`
 * license - id based on https://spdx.org/licenses/

Those additional fields would make it into the `metadata.json` file, and would over time become searchable. 

_Note: this is an additive change and would not break existing archives_

**Comment by cdupuis** [comment]
cc @WillGardella @ddgenome @jessitron

**Comment by ddgenome** [comment]
Seems more an more like `package.json` to me.

**Comment by cdupuis** [comment]
Similar but not the same. `package.json` is dev only and not required by the runtime or our tooling.

**Comment by cdupuis** [comment]
Replaced by #197
