### ISSUE TITLE
Tweak chocolatey package version to workaround semver limitation from nuget

### ISSUE THREAD

**Issue by Lawouach** [atomist/rug-cli#189]
As per Chris Burrell, chocolatey dies when installing the CLI due to the version number we set: M.N.A-m.1 The last dot, before the number 1, is [not supported by nuget](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning) and likely chocolatey.

```
Chocolatey v0.10.3
Upgrading the following packages:
rug-cli
By upgrading you accept licenses for the packages.
'1.0.0-m.1' is not a valid version string.
Parameter name: version
```

As this is a valid semver we are keen on keeping, we must likely tweak the version for choco packages when we build them.

**Comment by Lawouach** [comment]
Playing locally with removing the last offending dot, chocolatey quits complaining and carries on. So we have indeed to tweak that version.

**Comment by cdupuis** [comment]
@Lawouach is that still open?

**Comment by Lawouach** [comment]
Shouldn't with the merge from this afternoon, no.
