### ISSUE TITLE
Rug shell cannot run builtin commands on Linux

### ISSUE THREAD

**Issue by Lawouach** [atomist/rug-cli#200]
The rug shell cannot run builtin commands, such as `cd` or `history` because they are builtin commands, thus not found in the PATH.

The shell relies on RunProcess which uses ProcessBuilder. To be able to run those builtin commands, we would have to wrap the given command in a call such as `bash -c "..."`. 

This is mostly a problem for builtin gestures relying on the `cd` builtin command as it fails on Ubuntu (likely on any Bash I guess) and prevents the gesture from completing.

See for example:

```
~/dev/atomist/ (1.0.0-m.3)
rug → /history

Cannot run program "history" (in directory "/home/sylvain/dev/atomist"): error=2, Aucun fichier ou dossier de ce type

Cannot run program "history" (in directory "/home/sylvain/dev/atomist"): error=2, Aucun fichier ou dossier de ce type
```

whereas with `pwd`, an actual binary found in the PATH:

```
~/dev/atomist/ (1.0.0-m.3)
rug → /pwd
/home/sylvain/dev/atomist
```

**Comment by cdupuis** [comment]
Closing this for now as there is no way to run real shell commands.
