### ISSUE TITLE
Render test ‘failure’ in green if actually expected

### ISSUE THREAD

**Issue by russmiles** [atomist/rug-cli#201]
When running tests and a failure is expected, the failure text should render in green rather than the red currently shown.

**Comment by cdupuis** [comment]
The CLI renders the colours based on what is coming out of Rug. What is Rug reporting for those expected failures?

**Comment by ddgenome** [comment]
That's the trick, because the steps are actually failing. Perhaps the answer is to not report the status of When steps, which may fail intentionally, only report on Given and Then steps.

**Comment by cdupuis** [comment]
Right, I think that makes sense @ddgenome. I'll see if there is a way to detect a when step.

**Comment by cdupuis** [comment]
@ddgenome or @russmiles do you happen to have a test I can use to test the expected behaviour?

**Comment by ddgenome** [comment]
The rug-rugs repo has several tests that intentionally fail. For example, https://github.com/atomist/rug-rugs/blob/master/.atomist/tests/project/AddTypeScriptTest.feature#L34

**Comment by cdupuis** [comment]
@russmiles any reason to reopen this?

**Comment by russmiles** [comment]
No, seems odd as I don't recall hitting the button to action that. Anyway, closed again now.
