### ISSUE TITLE
Packages archives have a node_modules file

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#212]
Recently packaged files have an empty file, not directory, named `node_modules` at their root.

See atomist:travis-rugs:0.18.2 and atomist:rug-rugs:0.31.0 for examples.

**Comment by cdupuis** [comment]
I see that file on my filesystem so not sure what the CLI has to do with that.

**Comment by ddgenome** [comment]
I'm not positive it is caused by the CLI, but since it does the packaging and publishing, I thought this was a good place to start.

What do you mean by "I see that on my file system"? It's not in the git repo but it ends up in the archive. Maybe the Travis build script creates one at some point?

**Comment by cdupuis** [comment]
I see that file in a couple of rug archives I have my disk. No archives, just archives I work on.

**Comment by ddgenome** [comment]
I don't see it in any of my Rug projects.

**Comment by ddgenome** [comment]
I think I know what this is: I have the wrong path for the node_modules cache on the Travis CI build.
