### ISSUE TITLE
path expression that works in tests fails in prod

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-cli#215]
This path expression works in staging: ```/UserJoinedChannel()
       [/user::ChatId()
            [@isAtomistBot='true']]
       [/channel::ChatChannel()[/team::ChatTeam()/orgs::Org()]?[/Repo()]?]```

... but it worked in EventHandler Rug Tests in a prior version.

works in tests but not IRL:      [/channel::ChatChannel()[/team/org]?[/repo]?]
works IRL:                                [/channel::ChatChannel()[/team::ChatTeam()/orgs::Org()]?[/Repo()]?]

Note that I had to add the types, change "org" to "orgs", and I removed the "repo" name because I don't know what that relationship is called.

**Comment by ddgenome** [comment]
I'm not surprised the one that didn't work didn't work. For queries against cortex, we require both the relationship and type. This may belong in rug, as it knows where path expressions cross from file system to cortex.

**Comment by cdupuis** [comment]
This doesn't belong in the cli
