### ISSUE TITLE
editor parameter not validated

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-cli#26]
I ran `rug edit jessitron:elm-template:AddTextInput input_name=FavoriteColor`
and got an Elm parse exception when it used the input_name in a place where it's expected to start with a lowercase letter.
The editor's parameter requires that it start with a lowercase letter:
`param input_name: [a-z][\w]*`
This wasn't checked; the editor proceeded to execute and fail in a less-scrutable way.

parameters should be validated against their regex before running the editor, eh?

**Comment by cdupuis** [comment]
The parameters aren't checked by the CLI. The CLI just calls Rug to validate given parameters. Looks like this issue needs to be raised against rug.

**Comment by cdupuis** [comment]
CLI to rug to validate parameters: https://github.com/atomist/rug-cli/blob/master/src/main/java/com/atomist/rug/cli/command/AbstractParameterizedCommand.java#L24

**Comment by jessitron-stripe** [comment]
moved to https://github.com/atomist/rug/issues/31
