### ISSUE TITLE
Rug does not recognize local repository

### ISSUE THREAD

**Issue by mmoayyed** [atomist/rug-cli#29]
Running on Windows 10 with:

```
atomist/rug-cli.git (git revision 96e8923; last commit 2016-12-07)
```

I installed rug via choco and have been trying to go through the docs. Having install the common-editors locally via `rug install`, I can see the package is correctly installed. However when I run:

```
 rug describe editor atomist-rugs:common-editors:AddApacheSoftwareLicense20
```

I get the following:

```
No valid ARTIFACT provided, no default artifact defined and not in local mode.
```

If I provide `-l` in the current `common-editors` directory I can see the editor but if I leave that out or navigate to another project directory I can not describe or run/edit the editor.

```
> rug edit "atomist-rugs:common-editors:AddApacheSoftwareLicense20"

No valid ARTIFACT provided, no default artifact defined and not in local mode.
```

**Comment by cdupuis** [comment]
@mmoayyed, thanks for raising this. This error is due the use of numbers in the editor name. Try with any other editor in that archive, eg. AddReadme, and it will work.

That's not to say that this isn't a bug.

**Comment by mmoayyed** [comment]
Excellent. Thanks very much.

**Comment by cdupuis** [comment]
There is new version of the CLI 0.16.2 that provides a fix for that.
