### ISSUE TITLE
Improve `Parameter pattern must contain anchors:.*`error message

### ISSUE THREAD

**Issue by gotcha** [atomist/rug-cli#38]
Like in #37, more information should be given to mention what is wrong.
Even better, a hint of next possible steps.

**How to Reproduce:**
```
$ rug edit atomist-rugs:python-library:AddTravisCI
  Downloading atomist-rugs/python-library/maven-metadata.xml ← rugs (0kb) succeeded
Resolving dependencies for atomist-rugs:python-library:latest completed
Loading atomist-rugs:python-library:0.1.0 into runtime failed

Parameter pattern must contain anchors: .*
$ rug -v
rug 0.17.1
atomist/rug-cli.git (git revision 5a7f1f5; last commit 2016-12-13)
```

**Comment by cdupuis** [comment]
Yes, this is very annoying especially given that we actually don't tell what file is broken. We need more context like line number and column on this error.

It is related to a change in Rug. see https://github.com/atomist/rug/issues/31

**Comment by cdupuis** [comment]
This is now tracked at https://github.com/atomist/rug/issues/58
