### ISSUE TITLE
Run JS through Babel before eval-ing it in Nashorn

### ISSUE THREAD

**Issue by aengl** [atomist/rug-cli#45]
I currently run my NPM dependencies through Babel to make sure they are compatible with Nashorn. This could be done automatically in the backend.

My personal setup uses the ES2015 preset (https://babeljs.io/docs/plugins/preset-es2015/) combined with the object-assign plugin (https://babeljs.io/docs/plugins/transform-object-assign/).

Node libraries and other unwanted calls could be shimmed using the same approach, to improve compatibility and security. On top of that, by shimming those calls with meaningful exceptions it would greatly improve the readability of the stack traces.

**Comment by cdupuis** [comment]
Right now, this is to a priority.
