### ISSUE TITLE
Please improve the error message when TS can't be compiled

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-cli#51]
In a new Rug archive with a typescript editor, the install fails with an inscrutable error message.

```
$ rug install
Resolving dependencies for atomist-rugs:rug-upgrade:0.1.0 ← local completed
Loading atomist-rugs:rug-upgrade:0.1.0 ← local into runtime completed
  Generated META-INF/maven/atomist-rugs/rug-upgrade/pom.xml
  Generated .atomist/manifest.yml
  Generated .atomist/metadata.json
Generating archive metadata completed
Compiling script sources failed

com/atomist/rug/compiler/typescript/TypeScriptCompilerContext
```

To reproduce:

- generate a new Rug archive with atomist-rugs:rug-archive:NewRugArchive
- add a .ts editor to it
- rug install

**Comment by cdupuis** [comment]
You are working against an unsupported version of Rug I assume. 0.8.0- SNAPSHOT or so.

**Comment by cdupuis** [comment]
That is not an error message, that is an API change that has to be addressed in the CLI. I have that working already but can't release as there is no released Rug with those changes released.
