### ISSUE TITLE
Interactive prompts for parameters

### ISSUE THREAD

**Issue by jakubka** [atomist/rug-cli#54]
For users running complex editors with multiple parameters, it would be nice to be asked to enter parameters one by one with full description saying what individual parameter means.

This is helpful if user is not familiar with the editor and doesn't run it frequently.

As an author of the editor/generator, it would be great to just document one command to run and everything else will be prompted on the command line. Now I need to either assume that users are familiar with `describe` command or I need to document every param.

An example of such UI:
![13154228-5c9c-11e6-8c22-e5e74d91afc9](https://cloud.githubusercontent.com/assets/4806497/21649204/1c49b54c-d2a1-11e6-9f17-9734bd3b0d4e.png)

Current mode should stay for the automation purposes, but I am sure both modes can be elegantly combined...

**Comment by cdupuis** [comment]
How is something like the following: 

```
10:58 $ ../../atomist/rug-cli/target/rug-cli-0.20.0-SNAPSHOT-bin/rug-cli-0.20.0-SNAPSHOT/bin/rug edit EnableTravisForRugArchiveTS -l repo_slug=test/test -I
Resolving dependencies for atomist-rugs:travis-editors:0.7.0 ← local completed
Invoking TypeScript Compiler on ts script sources                                                                                                                                           
  Created .atomist/editors/EnableTravisForRugArchiveTS.js                                                                                                                                   
  Created .atomist/editors/UpdateTravisMaven.js                                                                                                                                             
Processing script sources completed
Loading atomist-rugs:travis-editors:0.7.0 ← local into runtime completed

Please enter values for following 5 missing parameter(s)

  Specify the Travis CI .org or .com endpoint
  pattern: ^\.(org|com)$, min length: 4, max length: 4
  → org [.org] : .org

  GitHub Personal Access Token of the repo owner with the following scopes: repo,
  write:repo_hook, user:email, and read:org, generated at
  https://github.com/settings/tokens; if the repo owner is an organization, the token must
  belong to a user in the Owner group of the organization
  pattern: ^[a-f0-9]{40}$, min length: 40, max length: 40
  → github_token [] : 233245678543245678543

  The URL for a Maven-compatible repository, without the trailing repository name, e.g., if
  the Maven repository URL is 'https://atomist.jfrog.io/atomist/rugs-release', then you
  would provide 'https://atomist.jfrog.io/atomist' for this value
  pattern: ^(?:https?|ftp)://[^\s]+$, min length: 7, max length: 100
  → maven_base_url [https://atomist.jfrog.io/atomist] : 

  Maven user with write access to the rugs-dev and rugs-release repositories under the Maven
  Base URL
  pattern: ^.*$, min length: 1, max length: 100
  → maven_user [] : maven_deploy

  API token or password for the Maven User
  pattern: ^.*$, min length: 1, max length: 100
  → maven_token [] : 234567897654324567897543

```

Does that make sense?

**Comment by cdupuis** [comment]
Yeah, there is a new switch on `edit` and `generate`.

I changed it so that _all_ parameters are being queried for, as otherwise it gets a bit odd to enter or not enter optional parameters as they would never be missing. But if a parameters is presented when invoking the command, the provided value will be the default. Does that make sense?

**Comment by cdupuis** [comment]
@jakubka, you can try this out now via `brew upgrade --HEAD rug-cli --fetch-HEAD`. Let me know if that this what you were thinking.

**Comment by jakubka** [comment]
> I changed it so that all parameters are being queried for, as otherwise it gets a bit odd to enter or not enter optional parameters as they would never be missing. But if a parameter is presented when invoking the command, the provided value will be the default. Does that make sense?

Yeah absolutely! This is actually the same behaviour as in cookiecutter.. except they take the defaults from the file, not from the cli params.

Let me try it now...

**Comment by jakubka** [comment]
Few weird things: 

- min/max length sometimes reported as -1
- I'm not sure how valueable is it to show a pattern.. as you can see on the screenshot, it can get messy. :) Maybe it can be shown only when the parameter is invalid?
- not sure if this is by design or not, but when you enter parameter value as the first param, it thinks it's a project_name.. also can be seen on the screenshot. Maybe all params should be required to be entered in format key=value?

![screen shot 2017-01-06 at 5 13 45 pm](https://cloud.githubusercontent.com/assets/4806497/21726237/d098f09c-d433-11e6-99eb-41656a6aaf3c.png)

I love it in general, thanks!

**Comment by cdupuis** [comment]
> min/max length sometimes reported as -1

That is good find. -1 means it is not defined. So maybe I should not display those then.

> I'm not sure how valueable is it to show a pattern.. as you can see on the screenshot, it can get messy. :) Maybe it can be shown only when the parameter is invalid?

It is indeed messy. The idea of displaying the regex if the parameter is invalid is a good idea.

> not sure if this is by design or not, but when you enter parameter value as the first param, it thinks it's a project_name.. also can be seen on the screenshot. Maybe all params should be required to be entered in format key=value?

So, yeah, the first parameter to a Generator is always considered the project_name.
