### ISSUE TITLE
eval fails when using local TS dependencies

### ISSUE THREAD

**Issue by aengl** [atomist/rug-cli#59]
Using rug 0.20.0

If a TS editor imports and uses a local TypeScript module, rug shows the following error:

```
<eval>:11:356 Expected } but found eof
//# sourceMappingURL=data:application/json;base64,...
```

It appears that tsc generates source maps but Nashorn can't handle them. Turning source maps off should fix that.

Demo project: https://github.com/blairehh/foobar-react-editors/tree/6000de0a46755b90e078c2096ece06410dbc670d

**Comment by cdupuis** [comment]
Argh, looks like Nashorn doesn't like the source maps. Odd. I'll disable them for the time being.

**Comment by cdupuis** [comment]
@kipz, didn't we fix this yesterday in the rug-typescript-compiler?

**Comment by kipz** [comment]
Yeah - also rug itself strips comments now, and source maps are to be loaded from external files for now until we figure why nashorn barfs.
