### ISSUE TITLE
Problem when importing packages directly

### ISSUE THREAD

**Issue by aengl** [atomist/rug-cli#61]
Most of my problems with CommonJS imports have been resolved, but there is one more minor issue:

tsc invoked from rug-cli fails when importing a package without specifying the path all the way down:

```
// Works:
import { JsNode } from 'js-transformabit/dist/Main';
// Does not work but should:
// import { JsNode } from 'js-transformabit';
```

The error is:
```
.atomist/editors/Test.ts(5,24): error TS2307: Cannot find module 'js-transformabit'.
import { JsNode } from 'js-transformabit';
-----------------------^
```

Invoking tsc locally resolves the dependency in both scenarios without problems.

tsc should automatically read this path from the dependency's package.json, by looking up `"main": "./dist/Main.js"`.

With this resolved I could probably simplify all the Rug imports into a single statement.

**Comment by aengl** [comment]
Forgot to mention, project demonstrating the problem: https://github.com/blairehh/foobar-react-editors/tree/1cb7c041a489496f2abaa6ba06734e8e6f130d0f

**Comment by cdupuis** [comment]
@kipz, what do you think about that?

**Comment by kipz** [comment]
@aengl the next release of the CLI will include fixes for both those import issues:

* non-relative node module imports
* relative TS imports

It's worth noting, that once this is released, you need to export your editors, not just set a var!

There is limited support for adding them automatically so as not to break things that are already using the old method, but please take the opportunity to move forward if you can.

e.g.

```typescript
export var editor = new SimpleEditor()
```

**Comment by aengl** [comment]
@kipz Thanks! I much prefer that, it is a lot more idiomatic. We already export our editors so we can invoke them internally for testing purposes.
