### ISSUE TITLE
Add search filter on generators

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-cli#72]
Please add a `--generator` command-line option to the `search` subcommand that filters out all non-generators from the results.

Since running just `rug search` seems to return all known rug archives, running `rug search --generator` should return all known generators.

**Comment by cdupuis** [comment]
I assume we may want `--editors` etc too, right?

**Comment by ddgenome** [comment]
Good point, perhaps allow multiple `--type TYPE` options where TYPE can be editor, generator, reviewer, etc.?
