### ISSUE TITLE
StackOverflowError when running an editor

### ISSUE THREAD

**Issue by aengl** [atomist/rug-cli#77]
Using rug 0.10.0 and rug-cli 0.21.0

Command is: `rug edit -ltX Test`

Repository: https://github.com/triforkse/js-transformabit-demos/tree/759aa38ced2e6378c2a9978a1d78533a43653b03

[trace.txt](https://github.com/atomist/rug-cli/files/716146/trace.txt)

**Comment by kipz** [comment]
Looks like a circular require dependency in your JS.

In the immediate term, we'll need to avoid these, but perhaps we could add update our common-js implementation to short-circuit in these scenarios.

**Comment by kipz** [comment]
Thanks for the report @aengl. Gonna close this and move over to https://github.com/atomist/rug/issues/195
