### ISSUE TITLE
404 when installing rug-cli with apt-get

### ISSUE THREAD

**Issue by janekdb** [atomist/rug-cli#79]
I see a 404 error and failure to install `rug-cli` when following .. on Ubuntu Trusty,

# Error

```
$ sudo apt-get install rug-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rug-cli
```

# Commands

http://docs.atomist.com/rug/rug-cli/rug-cli-install/

```
 1592  wget -qO - 'https://atomist.jfrog.io/atomist/api/gpg/key/public' | sudo apt-key add -
 1593  echo "deb https://atomist.jfrog.io/atomist/debian $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/atomist.list
 1594  sudo apt-get update
 1595  sudo apt-get install rug-cli
```

# 404s

```
W: Failed to fetch https://atomist.jfrog.io/atomist/debian/dists/trusty/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://atomist.jfrog.io/atomist/debian/dists/trusty/main/binary-i386/Packages  HttpError404
```

Attached is the log from` apt-get update`

**Comment by janekdb** [comment]
[rug-cli-agt-get-404.txt](https://github.com/atomist/rug-cli/files/719204/rug-cli-agt-get-404.txt)

**Comment by Lawouach** [comment]
Hi @janekdb,

I should really update the documentation abou this. Rug and the CLI require Java 8 which is not a native package on trusty, therefore we don't provide a repository for it.

You might want to install it manually for now I'm afraid until we figure it out. 

http://docs.atomist.com/rug/rug-cli/rug-cli-install/#manual-installation
https://github.com/atomist/rug-cli/releases

**Comment by Lawouach** [comment]
A quick update on this. I realise I forgot to comment.

We now support Ubuntu trusty but you need to install Java 8 yourself, either through a ppa or manually setting JAVA_HOME accordingly. http://docs.atomist.com/rug/rug-cli/rug-cli-install/#debianubuntu

**Comment by janekdb** [comment]
This is what I had used prior to trying to `apt-get` the cli if it's of any value,

```

# Install Java 8 SDK on Ubuntu Trusty 14.x
# http://www.ubuntuupdates.org/ppa/webupd8_java
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
sudo apt-get -y install oracle-java8-installer

java -version
```
