### ISSUE TITLE
rug describe should detect what to describe

### ISSUE THREAD

**Issue by tanya-coding** [atomist/rug-cli#98]
Currently, you can run `rug describe archive group:artifact` or `rug describe editor|generator|executor|reviewer group:artifact:name`.  It would be nice if `rug describe` would detect what to describe automatically based on the archive or artifact path.  This assumes that all operations within an archive have unique names which is probably what we would want anyway.

**Comment by Lawouach** [comment]
Oh yeah, this is a great idea!

**Comment by jessitron** [comment]
+1 to this from @WillGardella 

James says we should enforce uniqueness in Rug
but even if we don't we can handle that in the CLI (print both or something)

we want this change in the CLI independent of that
